### ISSUE TITLE
Not related with repo, please read

### ISSUE THREAD

**Issue by JoaoLages** [ajaanbaahu/TwitBitCoin#1]
Sorry to contact you this way. It was the only way that I have found, unfortunately.

Did you post [this comment](https://stackoverflow.com/questions/43357732/how-to-calculate-the-cosine-similarity-between-two-tensors#comment82368664_46057597) on stackoverflow? If so, can we discuss on how you solve that problem?

**Comment by ajaanbaahu** [comment]
Hi João,

Unfortunately I was not able to find a solution to solve that problem owing
to the limited experience I have with TF.

**Comment by JoaoLages** [comment]
Ok, thank you anyway.
